---
version: "3.9"
services:
  metronome:
    image: aminenaim/metronome:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: metronome
    network_mode: host
    environment:
      TIME: 900 # 15 min check
    volumes:
      - /Users/torguet/dev/Python/metronome/config:/config
      - /Users/torguet/dev/Python/metronome/ics:/ics
    restart: unless-stopped